### ISSUE TITLE
BUG: cmd and args are not parsed correctly

### ISSUE THREAD

**Issue by Bianco95** [interTwin-eu/interlink-slurm-plugin#10]
The bug appears during the execution of the hello world test from   _https://github.com/landerlini/vk-test-set/blob/main/vktestset/templates/000-hello-world.yaml_  .
It seems that args are not parsed correctly, in details, the test is requesting 
`command: ["/bin/bash", "-c"]
 args: ["echo hello world"]`
but the `hello world` is not printed, meaning that the arguments are not parsed correctly.
A possible solution to solve this problem would be to create a bash file with the contents of the command and the args and then send this bash file to the container.  So the content of the bash file for this example would be something like

```bash
#!/bin/bash

/bin/bash -c 'echo hello world' 
```

**Comment by Surax98** [comment]
Addressed in release [0.2.6](https://github.com/interTwin-eu/interlink-slurm-plugin/releases/tag/0.2.6)
Closing for now, but it should probably be reviewed to check if it is properly done
