### ISSUE TITLE
rename aux.go

### ISSUE THREAD

**Issue by antoinetran** [interTwin-eu/interlink-slurm-plugin#16]
# Short Description of the issue

In Windows, `aux` is a reserved name. It is not possible to name a file like this, or else an invalid name error appears. Even for `aux.go`. Thus it is not possible to clone in Windows this repository.

## Environment

- Operating System: Windows
- Other related components versions:

## Logs, stacktrace, or other symptoms

```shell
output
```

# Summary of proposed changes

If it is not too much of a hassle, can someone rename the file? I can see similar error like https://github.com/mhausenblas/burry.sh/issues/13

**Comment by dciangot** [comment]
+1 I didn't find it to be a good name anyway. @antoinetran if you have any good name in mind please go ahead and feel free to propose a PR. Otherwise I'll let @Surax98  come up with one.

The change should have 0 impact everywhere else.

**Comment by Surax98** [comment]
Yeah, literally 0 impact. Just let me know if I have to think about anything or not

**Comment by dciangot** [comment]
looking at the content, to me either prepare.go or preparation.go is kind of fine. They are all functions meant to prepare the slurm submission. Maybe prepare is slightly better. I no one object, I'd go with prepare.go

**Comment by Surax98** [comment]
Or just... func.go? I mean, the majority are to prepare  for the slurm submission, but some are just wrappers or to check if a value is stored in memory.

**Comment by dciangot** [comment]
in general is useful to avoid generic name where to put "everything else".

so, if there is something other then preparation, we *might* think of moving that function somewhere else. Also, checking if a value is in memory can be considered as a preparatory step.

so I still suggest prepare.go

**Comment by Surax98** [comment]
Addressed in [bbf43b3](https://github.com/interTwin-eu/interlink-slurm-plugin/commit/bbf43b3890db8059db7569c8801cd3ff0eeaa74d)
