### ISSUE TITLE
Escape quotes when in ENV

### ISSUE THREAD

**Issue by dciangot** [interTwin-eu/interlink-slurm-plugin#28]
# Short Description of the issue

As per #27 we should check and escape quotes when present in the content of the env variables.

## Environment

- Operating System:
- Other related components versions:

## Logs, stacktrace, or other symptoms

```shell
output
```

# Summary of proposed changes

**Comment by antoinetran** [comment]
This ticket should be closed? Because #27 already checks and escape quote.
